casepro/backend/junebug.py
casepro/backend/tests/test_junebug.py
casepro/settings_common.py
pip-freeze.txt

This supercedes https://github.com/praekelt/casepro/pull/5 , which was comparing to the incorrect branch

Add sending outbound messages to Junebug endpoint

---

casepro/msgs/models.py
casepro/msgs/tests.py
casepro/msgs/views.py
casepro/settings_common.py

**DEL4.2**
Customised search endpoint that also filters FAQs by:
- Language
- Label

OPENHELPD-14 FAQ Search API Endpoint

---

.gitignore
casepro/msgs/faq_csv_example.csv
casepro/msgs/tasks.py
casepro/msgs/views.py
casepro/settings_common.py
media/test_imports/faq_good_import.csv
templates/msgs/faq_list.haml

**DEL12.1**
Create languages from headers (use 6-letter codes)
Labels should be in the last columns (multiple allowed)

OPENHELPD-14 FAQ Batch Upload

---

karma/test-services.coffee
static/coffee/modals.coffee

Additional tests required for frontend:

OPENHELPD-15 Additional frontend tests

---

.travis.yml
casepro/msgs/tasks.py
casepro/msgs/tests.py
media/test_imports/faq_bad_import_labels.csv

Testing in #12 was incomplete.

OPENHELPD-14 FAQ Batch upload testing

---

karma/test-controllers.coffee
karma/test-services.coffee
static/coffee/controllers.coffee
static/coffee/services.coffee

Same PR as #34, but against the correct branch.

Add base data pod angular components

---

casepro/cases/forms.py
casepro/cases/migrations/0038_partner_timezone.py
casepro/cases/models.py
casepro/cases/tests.py
casepro/cases/views.py
casepro/test.py
templates/cases/partner_list.haml

OPENHELPD-42 Add timezone to partner and user

---

casepro/cases/forms.py
casepro/cases/migrations/0038_partner_timezone.py
casepro/cases/migrations/0039_partner_description.py
casepro/cases/models.py
casepro/cases/tests.py
casepro/cases/views.py
casepro/test.py
templates/cases/partner_list.haml

OPENHELPD-44 Add description to partner

---

karma/test-services.coffee
static/coffee/services.coffee

We need to add a method to the service for triggering pod actions.

Add action support to PodApi angular service

---

karma/test-directives.coffee
templates/cases/case_read.haml

At the moment we use it as an attribute.

Use element for cpPod directive

---

casepro/pods/base.py
casepro/pods/tests/test_views.py
casepro/pods/tests/utils.py
casepro/pods/views.py

Continued from here: https://github.com/praekelt/casepro/pull/51
New PR to avoid merge issues with previous PR.

Backend changes for pod actions - 2

---

karma/test-directives.coffee
karma/test-services.coffee
static/coffee/services.coffee
static/less/pods.less
static/templates/pod.html
templates/cases/case_read.haml

This ticket is for changing the base pod's angular components to show action buttons from data read from pods.

Draw actions from read pod data

---

casepro/cases/models.py
casepro/cases/tests.py
casepro/cases/views.py
karma/test-controllers.coffee
karma/test-modals.coffee
karma/test-services.coffee
static/coffee/controllers.coffee
static/coffee/modals.coffee
static/coffee/services.coffee
templates/partials/modal_assign.haml

Now that we have a user field on the Case model, we need some UI to be able to assign a case to a user within the partner.
Edit: This will only cover reassigning a case. Creating a case will be covered in another issue.

Add user selection when assigning a case

---

casepro/settings_production.py

This pull request is against the `staging` branch since that deals with the
QA setup for this project.

Read SENTRY_DSN from environment

---

casepro/cases/models.py
casepro/cases/tests.py
casepro/cases/views.py
casepro/profiles/tests.py
casepro/profiles/views.py
casepro/statistics/models.py
casepro/statistics/signals.py
casepro/statistics/tests.py
setup.cfg
templates/orgs_ext/org_home.haml

Includes open, closed and total case counts.

Show case counts for partners.

---

casepro/cases/tests.py
casepro/cases/views.py
casepro/statistics/migrations/0008_dailyminutetotalcount.py
casepro/statistics/migrations/0008_minutetotalcount.py
casepro/statistics/models.py
casepro/statistics/signals.py
casepro/statistics/tasks.py
casepro/statistics/tests.py
casepro/utils/__init__.py
casepro/utils/tests.py
templates/orgs_ext/org_home.haml

Record metric of minutes elapsed until initial response to a case

Add average time to initial response metric

---

casepro/statistics/models.py
casepro/statistics/tests.py

This has PR #91 merged in so review that one first before this one.
Once #91 lands this will be easier to review.

Add case counts to partner exports.

---

casepro/statistics/models.py
casepro/statistics/tests.py
static/coffee/controllers.coffee
templates/orgs_ext/org_home.haml

This is the same as #107 except not having `staging` merged in.
I've cherry picked the commits from there into here to make reviewing and merging easier.

Add export button for Users to the UI (Take 2)

---

casepro/msg_board/__init__.py
casepro/msg_board/migrations/0001_initial.py
casepro/msg_board/models.py
casepro/msg_board/tests.py
casepro/msg_board/urls.py
casepro/msg_board/views.py
casepro/settings_common.py
pip-freeze.txt
static/coffee/services.coffee
templates/msg_board/comment_list.haml

This addresses comments raised in rapidpro/casepro#142

Implement feedback from Rowan

---

static/less/cases.less
templates/partials/modal_reply.haml

*Reply UI additions*
- More condensed layout
- Increased modal's max height
- Removed labels in filter box to save space
- Removed search button, when typing a keyword or label, it will auto filter results
- Left aligned FAQ results
- Label tags added to FAQ results
@Mitso Please Review
**Before:**
**After:**

reply-ui additons

---

templates/smartmin/users/login.haml

Added password requirement text to Login page
@Mitso please review
**Before:**
**After:**

password requirements

---

templates/cases/inbox_messages.haml

Flag icon colour change
@Mitso please review
**Before:**
**After:**

flag color update

---

static/less/cases.less

Wrapping issue on FAQ Details page
@Mitso please review
**Before:**
**After:**

word wrap fix

---

casepro/settings_production.py
pip-freeze.txt

This is to temporarily remove the registration pod in order to fix the staging build.

Remove Registration pod

---

casepro/cases/tests.py
casepro/cases/views.py
casepro/contacts/models.py
casepro/contacts/tests.py
casepro/msgs/tests.py
casepro/orgs_ext/tests.py
casepro/settings_common.py
casepro/statistics/models.py
casepro/test.py
karma/test-controllers.coffee
karma/test-services.coffee
karma/test-utils.coffee
pip-freeze.txt
static/coffee/controllers.coffee
static/coffee/services.coffee
static/coffee/utils.coffee
templates/cases/case_read.haml
templates/cases/inbox_base.haml
templates/cases/inbox_messages.haml
templates/cases/inbox_outgoing.haml
templates/contacts/contact_read.haml
templates/partials/directive_contact.haml

I created this PR because the tests were failing locally after the merge. It looks like that isn't the case here so I'm going to land it

Update staging with upstream changes

---

static/less/cases.less
templates/msgs/faq_read.haml

@miltontony please review
Read label style moved to FAQ read template

faq read label fix

---

karma/test-controllers.coffee
static/coffee/controllers.coffee

added a 10second refresh to the messages inbox

add 10sec refresh interval

---

casepro/msgs/forms.py

@miltontony please review and check if I did the branches properly.

Fixed the faq translation save

---

casepro/cases/views.py
templates/cases/inbox_messages.haml

Change the fixed width of the column based on the SITE_CONTACT_DISPLAY field

Use fixed width for contact display

---

casepro/settings_production.py

This PR changes the "SITE_MAX_MESSAGE_CHARS" setting.

Message max chars setting change

---

pip-freeze.txt

Installs the subscription pod from the develop branch on the github repo so that it can be tested before we create a release.

Install subscription pod from github

---

Dockerfile
casepro/backend/junebug.py
casepro/backend/tests/test_junebug.py
casepro/msgs/management/commands/export_messages.py
casepro/settings_production.py
pip-freeze-praekelt.txt

Merges the latest from develop (which has gone through staging)
into the docker-production branch

New docker-production release

---

casepro/backend/junebug.py
casepro/backend/tests/test_junebug.py

This will allow the Hub to take actions or report based on channel details.

Send channel ID to hub when a message is sent

---

Dockerfile

This commit updates the dockerfile to reflect py3.6

This commit updates the dockerfile to reflect python3.6
