praekeltfoundation/casepro

- casepro/backend/__init__.py
- casepro/backend/rapidpro.py
- casepro/backend/tests/test_rapidpro.py
- casepro/urls.py
For our new backend, we're going to need a way to register URLs, but this should be backend dependant.
The plan is to add a function to the BaseBackend definition that will generate a list of url patterns that should be registered. The current RapidPro backend will implement this function as just returning an empty list.
This function then needs to be called in the correct place to register the URLs.
> Add backend function for getting url patterns

- casepro/msgs/forms.py
- casepro/msgs/migrations/0048_language.py
- casepro/msgs/models.py
- casepro/msgs/tests.py
- casepro/msgs/urls.py
- casepro/msgs/views.py
- casepro/settings_common.py
- casepro/test.py
- casepro/utils/__init__.py
- static/coffee/controllers.coffee
- static/coffee/services.coffee
- templates/frame.haml
- templates/msgs/language_list.haml
- templates/msgs/language_read.haml
Add a language model that can be managed in a similar fashion to the FAQ model.  This will be used for translation of FAQs.  Languages should also be created via the batch uploads automatically, but this will be handled in issue #12.
> OPENHELPD-14 Creation and Management of Languages

- casepro/backend/junebug.py
- casepro/backend/tests/test_junebug.py
- casepro/settings_common.py
We should add an identity store lookup for outbound messages where we have a contact, but no URN, in order to get the contact's address.
> Add Identity store lookup for outbound messages

- casepro/backend/junebug.py
- casepro/backend/tests/test_junebug.py
Currently for the Junebug backend outbound messages, we check the identity for a list of addresses.
An identity, however, might have a communicate_through parameter, in which case we should get the addresses for the identity specified by communicate_through, instead of the current identity.
> Get communicate_through addresses if available

- casepro/backend/junebug.py
- casepro/backend/tests/test_junebug.py
Contacts won't be deleted in the Identity Store so we shouldn't sync deleted contacts. Opted out Identities will be sent to Casepro via a webhook and handled in a different PR.
> Remove Identity store deleted sync and tests

- casepro/utils/__init__.py
- casepro/utils/tests.py
Currently, the `uuid_to_int` function turns a uuid into an integer within the range of an `IntegerField`. This causes problems as most of the url regexes don't account for negative IDs, so it results in 404s for messages with negative IDs. We need to change to `uuid_to_int` function to only return positive number.
> Make UUID to int function only return positive integers

- casepro/backend/junebug.py
Currently, we just use `datetime.now()` for the timestamp for incoming Junebug messages. We need to add timezone information to this to fix tests that were broken by the upstream code.
> Add timezone information when creating inbound message Junebug backend

- casepro/pods/base.py
- karma/test-directives.coffee
- static/coffee/directives.coffee
To be consistent with the naming convention used for `cpContact`.
> Rename pod directive to cpPod

- karma/test-services.coffee
- static/coffee/services.coffee
The plan is to change the service to make actions requests that look something like this:
```
POST /pods/action/<pod_id>/
{
case_id: <case_id>,
action: {
type: <action_type>,
payload: {...}
}
}
```
> Update PodApi service sending of actions request to match api change

- static/templates/pod.html
At the moment we use `{{`s, which angular accepts, but the convention in this project is to use `[[`s.
> Use `[[`s in angular templates

- karma/test-controllers.coffee
- static/coffee/controllers.coffee
We need to change the base pod controller to:
- support triggering actions
- fetch new pod data after an action has been triggered, and update the scope with the new data
> Update base pod controller to support triggering actions

- karma/test-controllers.coffee
- static/coffee/controllers.coffee
Triggering a pod action causes a new note to be created for the case. We need to be able to redraw the case actions once an action has been triggered to draw the new note.
> Update case actions after triggering a pod action

- karma/test-controllers.coffee
- static/coffee/controllers.coffee
We need to un-disable when action completes, regardless of the result.
> Pod actions remain disabled after unhandled errors

- casepro/pods/tests/test_views.py
- casepro/pods/views.py
We need to record the user's name on the case action we record when the user triggers a pod action.
> Include user's name on pod action case actions

- casepro/pods/base.py
We added a few more fields:
- `busy_text`: To show different text when actions are busy
- `confirm`: Whether a confirmation modal should be shown
> Update documented format for actions after UI changes

- casepro/cases/models.py
- casepro/cases/tests.py
- casepro/cases/views.py
- karma/test-controllers.coffee
- karma/test-modals.coffee
- karma/test-services.coffee
- static/coffee/controllers.coffee
- static/coffee/modals.coffee
- static/coffee/services.coffee
- templates/partials/modal_newcase.haml
We have added the ability to assign a user to a case when reassigning a case, now we should add the ability to assign a user to case when creating the case.
The plan of action is to add the user dropdown field to the modal used to create cases, similarly to how we added it to the modal for reassigning a case.
> Add user selection when creating case

- casepro/cases/models.py
- casepro/cases/tests.py
- casepro/msgs/tests.py
- templates/cases/inbox_cases.haml
When viewing the list of cases, if there is also a user assigned to the case, we should show it next to the partner name.
> Show assigned user in case list

- casepro/cases/migrations/0041_caseaction_user_assignee.py
- casepro/cases/models.py
- casepro/cases/tests.py
- templates/cases/case_read.haml
Currently, the case notes for assignment and reassignment only show the partner, we need to change this to show both the partner and the user, if the case was assigned/reassigned to both a partner and a user.
> Add user to assign case note

- templates/cases/inbox_cases.haml
Currently, the partner and user are shown in two separate labels in the case list. The suggestion is to have it appear as `Partner (User)` in a single label.
> Have assigned user appear in same string in case list

- casepro/cases/migrations/0046_auto_20160816_1421.py
- casepro/cases/models.py
- casepro/cases/tests.py
- casepro/cases/views.py
- casepro/test.py
Currently, to generate the timeline for the case detail view, it relies on there being an `initial_message` attribute with a message attached to find the beginning of the timeline. If there is no `initial_message`, it currently breaks. This behaviour should be changed to setting the start date to the case creation date, if the `initial_message` is `None`.
> Have cases view not rely on initial_message

- casepro/cases/models.py
- casepro/cases/tests.py
Currently, the exports assume that there is an `initial_message` field that is not `None`. This should be changed so that it still works when `initial_message = None`.
> Have case exports not assume initial_message

- casepro/backend/__init__.py
- casepro/backend/junebug.py
- casepro/backend/rapidpro.py
We want to be allow Casepro to create contacts. The first step to this is to add a `push_contact` function to the backend, to allow contacts that are created on the casepro side to be created on the backend at the same time.
> Add push_contact function to the backend

- casepro/contacts/migrations/0024_auto_20160822_1224.py
- casepro/contacts/models.py
We want to be allow Casepro to create contacts. The second step to this is to allow the UUID field on contacts to be nullable. This way, we can create a contact with a `null` UUID field, and have the field be set to the appropriate value when it is pushed to the backend.
> Change contact's uuid field to be nullable

- casepro/backend/__init__.py
- casepro/backend/junebug.py
- casepro/backend/tests/test_junebug.py
We want to be allow Casepro to create contacts. Once we have completed the two steps of adding a `push_contact` function to the backend, and making the UUID field on a contact nullable, we can now implement the `push_contact` function for the Junebug backend.
> Implement push_contact for Junebug backend

- casepro/settings_production.py
It's disabled by default unless a TESTING flag is set to True
> enable sending of emails

- karma/test-controllers.coffee
- karma/test-services.coffee
- static/coffee/controllers.coffee
- static/coffee/services.coffee
- templates/orgs_ext/org_home.haml
Admins should have a global view.
> Show organisation names and split users in Admin view

- casepro/cases/models.py
- casepro/cases/tests.py
- casepro/cases/views.py
- casepro/contacts/models.py
- karma/test-controllers.coffee
- karma/test-services.coffee
- static/coffee/controllers.coffee
- static/coffee/services.coffee
- static/templates/modals/create_case.html
- templates/cases/inbox_messages.haml
Now that we have done all the backend preparation work for being able to create a case without the `initial_message` field, we can move onto creating the modal (and the button to bring up the modal), which will allow users to create a case, by specifying the URN and description, without needing the initial message.
> Add modal for creating case without message

- static/less/cases.less
Added some line breaking rules to the FAQ table's Questions and Answers columns
@Mitso Please review
**Before:**
**After:**
> faq wrapping fix

- static/coffee/controllers.coffee
Insert a confirmation prompt/popup before a message is selected to be unflagged 
note: CONFIRMATION SHOULD ONLY BE TRIGGERED WHEN IN THE FLAGGED FILTER VIEW, not in the Inbox.
@Mitso please review
> un-flag confirmation prompt added

- casepro/msgs/tasks.py
- casepro/utils/__init__.py
- casepro/utils/tests.py
There were a few problems with python3 support.
1. DictReader doesn't seem to default to text mode when opening files
2. The keys() method on a dictionary no longer returns a list in python 3 (it returns a view object)
3. When merging the code from upstream I failed to spot some removed code
I've already cherry-picked the first two commits into https://github.com/rapidpro/casepro/pull/117 so that they will land upstream eventually
> Small fixes for python3 support

- casepro/msgs/models.py
- casepro/msgs/tests.py
- templates/cases/inbox_base.haml
*Requirements*
- Helpdesk staff would also like to see the label ‘population’ of the archive, similar to Inbox. 
- Suggestion: Show labels (such as Compliment, Complaint, Opt Out, etc) underneath Archive as well in order to show how many messages have been responded to within each label. 
- They would also like to click on a label under Archive in order to view all ‘Compliments’ that have been archived, for example.
- the labels under Inbox and Archive should be collapsable
> add labels to archive folder

- casepro/backend/junebug.py
- casepro/backend/tests/test_junebug.py
Currently, we're pulling all the identities that need to be synced into memory, and then we are processing them.
This causes issues with memory usage, which can cause the sync task to be killed halfway through.
This PR aims to resolve this by only processing one page of results at a time.
> Sync identities one page at a time

- casepro/backend/junebug.py
- casepro/backend/tests/test_junebug.py
Currently, if the language field is longer than 3 characters, the sync fails. This is due to the language field having a character limit of 3 in the database. If the language field is longer than this, then we should truncate the field before storing it on the contact.
> Fix error on long language field imports

- Dockerfile
@JayH5 pointed out that the upstream django-bootstrap container already has nginx installed.
I'm pretty sure we could stop using the specific django.conf in this repo and just use the upstream one. But not sure enough to make that change yet.
> Stop installing nginx in Docker

- casepro/settings_production.py
I didn't realise that the IDENTITY_API_ROOT really is just the root (because it uses some older code to connect to the identity store) whereas the new API client needs to include the path to the API.
> Append `api/v1/` to the pods identity store URL

- casepro/settings_production_momza.py
We started using the identity store and the hub to fetch this information, but unfortunately the field names are different depending on which service the info is coming from.
These 2 fields are already displayed in the CasePro interface so it makes sense to not use the pod at all for them.
> Remove cell number and language from pod

- casepro/backend/junebug.py
- casepro/backend/tests/test_junebug.py
Use a blank string rather than `None` as the default value for the channel_id string (this is as per DRF recommendations)
> Default channel id to empty string

- casepro/backend/junebug.py
- casepro/backend/tests/test_junebug.py
- casepro/settings_common.py
- casepro/settings_production.py
- pip-freeze.txt
This change will allow us to configure Casepro to use a router based channel, the url is not `/channels/<channel-id>/messages/` but something like `/routers/<router-id>/destinations/<destination-id>/messages/`.
Currently the url is built in the code, this PR allows us to rather specify it completely.
> Update Junebug urls for routing

- Dockerfile
Currently the Docker image won't build. See #227.
This PR fixes the build and streamlines it a bit: should end up with a smaller image due to combining all apt-get into a single line and running `apt-get clean` and `apt-get autoremove`.
> bumping docker base image from jessie to the latest praekelt django docker image

- docker/nginx.conf
- docker/supervisor.conf
- docker/supervisord.conf
Django bootstrap has changed the folder from `/var/run` to just `/run`, so we need to change it here in our config as well
> Change /var/run to /run
